import math
a = int(input())
resultado1 = (a**2)
resultado2 = a ** (1/2)
resultado3 = a ** (1/3)
resultado4 = math.pi / a
resultado5 = math.e * a
resultado6 = math.log(a,7)
resultado7 = math.log (a,10)
resultado8 = math.log (a,math.e)
resultado9 = math.exp (a)
print(resultado1)
print(resultado2)
print(resultado3)
print(resultado4)
print(resultado5)
print(resultado6)
print(resultado7)
print(resultado8)
print(resultado9)